version: "3.6"
services:
  api:
    build: "./"
    ports:
      - "4000:4000"
    volumes:
      - ".:/code"
    depends_on:
      - postgres

  postgres:
    image: "postgres:13"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "community_dev"

volumes:
  postgres_data: {}
